# About the auteurs & contributors of Arabesque {#authors}

Françoise BAHOKEN, geographer & cartographer </br> 
Research scientist, Université Gustave Eiffel/AME/ </br>
_Scientific coordination (coord.), conception and documentation_

Étienne CÔME, statistical & computer scientist</br>
Research scientist, Université Gustave Eiffel/COSYS/</br>
_Development (coord.) and conception_

Laurent JÉGOU, geographer & cartographer </br>
Teacher-researcher, Université Toulouse 2 / UMR 5193 LISST</br>
_Conception (co-coord.)_

Grégoire LE CAMPION, statistician </br>
Engineer, CNRS/UMR Passages </br>
Conception

Marion MAISONOBE, geographer </br> 
Research scientist, CNRS/UMR Géographie-Cités/PARIS </br>
Conception

Nicolas ROELANDT, geomatician </br>
Engineer, Université Gustave Eiffel/AME/ </br>
Conception, documentation

**Trainees**

Thomas BAPAUME, data scientist student (2018-2019) </br> 
ESIEE Paris 

Paul FABRE, geomatics student (2019-2020) </br>
ENSG Géomatique 


The team is open to any proposal of collaboration on the development/documentation of Arabesque. 



